version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: research-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: research_study
    ports:
      - "5442:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    container_name: research-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: local-minio
      MINIO_ROOT_PASSWORD: local-minio-secret
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: research-keycloak
    command: start-dev --http-port=8080 --hostname-strict=false
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: research-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgdata:
  miniodata:
