version: '3.8'

services:
  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=${JWT_SECRET:-dev-secret-key-change-in-production}
      - JWT_EXPIRES_IN=7d
    volumes:
      - ./prisma:/app/prisma
      - uploads:/app/uploads
    depends_on:
      - init-db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

  # Database initialization service
  init-db:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: sh -c "npx prisma migrate deploy && npx prisma db seed"
    environment:
      - DATABASE_URL=file:./dev.db
    volumes:
      - ./prisma:/app/prisma
    restart: "no"

  # Development server (optional - comment out for production)
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=dev-secret-key
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    profiles:
      - dev

volumes:
  uploads:
    driver: local
